### ISSUE TITLE
Tracking issue: renaming things and changing URLs

### ISSUE THREAD

**Issue by joepio** [ontola/atomic-data#135]
Sometimes, when designing URLs and naming things, we make mistakes. And with we, I typically mean myself. So at some time in the future (before 1.0), I'd like to fix a lot of wrong naming decisions in Atomic Data. This includes changing URLs.

- [ ] **Drive** => workspace
- [ ] **Subject** => id, or `@id`, or URL #3 #subject
- [ ] _camelCase_ for URLs => _kebab-case_. #16 
- [ ] Think about how ontologies are used in URLs (e.g. `atomicdata.dev/core/name` instead of `atomicdata.dev/properties/name`

Renaming these means breaking a bunch of apps and URLs, so this might have a huge impact. That's why we need:

- Migrations for Atomic-Server. Convert existing properties (and values!) to new ones. Re-build indexes.
- Redirect old definitions to new URLs, and make sure the redirects are processed in the right way.
